<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example.osgi</groupId>
    <artifactId>karaf-plugin-bug</artifactId>
    <version>1.1</version>
    <packaging>pom</packaging>
    <modules>
        <module>com.example.osgi.bundle1</module>
        <module>com.example.osgi.feature-repo-1</module>
        <module>com.example.osgi.bundle2</module>
        <module>com.example.osgi.feature-repo-2</module>
        <module>com.example.osgi.bundle3</module>
        <module>com.example.osgi.feature-repo-3</module>
        <module>com.example.osgi.bundle4</module>
        <module>karaf-assembly</module>

    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <karaf.version>4.4.8</karaf.version>
        <older.version>1.0</older.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.karaf.tooling</groupId>
                    <artifactId>karaf-maven-plugin</artifactId>
                    <version>${karaf.version}</version>
                    <configuration>
                        <javase>${java.version}</javase>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.12.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>5.1.9</version>
                    <extensions>true</extensions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.6.1</version>
                    <inherited>true</inherited>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
