<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.example.osgi</groupId>
        <artifactId>karaf-plugin-bug</artifactId>
        <version>1.1</version>
    </parent>
    <artifactId>com.example.osgi.bundle4</artifactId>
    <packaging>war</packaging>

    <dependencies>
        <dependency>
            <groupId>com.example.osgi</groupId>
            <artifactId>com.example.osgi.bundle2</artifactId>
            <version>1.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.example.osgi</groupId>
            <artifactId>com.example.osgi.bundle3</artifactId>
            <version>${older.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>6.1.21</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.cmpn</artifactId>
            <version>7.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.core</artifactId>
            <version>7.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bundle-manifest</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <supportedProjectTypes>
                        <supportedProjectType>war</supportedProjectType>
                        <supportedProjectType>bundle</supportedProjectType>
                    </supportedProjectTypes>
                    <instructions>
                        <Import-Package>jakarta.servlet,
                            jakarta.servlet.http, jakarta.servlet.annotation,
                            org.springframework.web.servlet,
                            org.springframework.context.annotation,
                            org.springframework.stereotype,
                            org.springframework.web.bind.annotation,
                            *;resolution:=optional
                        </Import-Package>
                        <Export-Package/>
                        <Private-Package>
                            com.example.osgi.bundle4.spring.*
                        </Private-Package>
                        <Bundle-ClassPath>.</Bundle-ClassPath>
                        <Bundle-Activator>com.example.osgi.bundle4.spring.OsgiServiceLocator</Bundle-Activator>
                        <Web-ContextPath>/api</Web-ContextPath>
                    </instructions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                    <webResources>
                        <resource>
                            <directory>target/classes</directory>
                            <filtering>false</filtering>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
